model_name: "Qwen/Qwen2.5-Coder-7B-Instruct"
input_dir: "./systemc_generation/dataset/geek/one_shot.json"

epoches: 1
batch_size: 64
tensor_parallel_size: 1
gpu_memory_utilization: 0.9
dtype: "bfloat16"

root_name: "dataset"
obj_dataset: "geek"
output_dir_name: "output"
