model_name: "codellama/CodeLlama-7b-Instruct-hf"
input_dir: "./systemc_generation/input_data/one_shot_new.json"

epoches: 20
batch_size: 64
tensor_parallel_size: 2
gpu_memory_utilization: 0.9
dtype: "bfloat16"

root_name: "dataset"
obj_dataset: "geek"
output_dir_name: "output"
