model_name: "bigcode/starcoder2-7b"
input_dir: "./systemc_generation/input_data/starcoder/one_shot_new.json"

epoches: 20
batch_size: 64
tensor_parallel_size: 2
gpu_memory_utilization: 0.9
dtype: "float32"

root_name: "dataset"
obj_dataset: "geek"
output_dir_name: "output"
