model_name: "Qwen/Qwen2.5-Coder-32B-Instruct"
input_dir: "./systemc_generation/input_data/qwen/one_shot_new.json"

epoches: 5
batch_size: 64
tensor_parallel_size: 2
gpu_memory_utilization: 0.9
dtype: "bfloat16"

root_name: "dataset"
obj_dataset: "geek"
output_dir_name: "output"
